namespace :genres do 
  desc "Creating genres"
  task :create => ['environment'] do
		Genre.create(:name => "Breakbeat | Electro")
		Genre.create(:name => "Broken Beat/Nu Jazz")
		Genre.create(:name => "General Chart, Dance & R&B")
		Genre.create(:name => "Disco | Nu Disco")
		Genre.create(:name => "Downtempo: Vocal | Lounge | Dub")
		Genre.create(:name => "Downtempo: Experimental/Electronic")
		Genre.create(:name => "Drum &amp; Bass")
		Genre.create(:name => "Euro Dance | Pop Dance")
		Genre.create(:name => "Funk/Rare Groove")
		Genre.create(:name => "Bassline | Speed Garege")
		Genre.create(:name => "Dubstep/Grime")
		Genre.create(:name => "UK Funky | UK Garage | 2 Step Garage")
		Genre.create(:name => "Hardcore | Hardstyle")
		Genre.create(:name => "Gabba")
		Genre.create(:name => "Hardstyle | Jumpstyle")
		Genre.create(:name => "UK Hardcore | Nu Rave")
		Genre.create(:name => "Hip Hop | R&B")
		Genre.create(:name => "Deep House")
		Genre.create(:name => "Electro House | Electroclash")
		Genre.create(:name => "Funky House | Vocal House | Disco House | Soulful House")
		Genre.create(:name => "Hard House")
		Genre.create(:name => "Minimal House | Tech House")
		Genre.create(:name => "Progressive House")
		Genre.create(:name => "Scouse House | Bouncy House")
		Genre.create(:name => "Jazz")
		Genre.create(:name => "Reggae Classics | Oldies | Ska")
		Genre.create(:name => "Dancehall | Regga | Reggaeton")
		Genre.create(:name => "Dub")
		Genre.create(:name => "Roots Reggae | Lovers Rock | One Drop")
		Genre.create(:name => "Rock | Indie")
		Genre.create(:name => "Techno")
		Genre.create(:name => "Hard Trance")
		Genre.create(:name => "Pop Trance")
		Genre.create(:name => "Psychedelic Trance | Goa Trance")
		Genre.create(:name => "Uplifting Trance | Progressive Trance")
	end
end